site:
  title: Example Project
  start_page: example:ROOT:index.adoc
  url: /

urls:
  latest_version_segment_strategy: redirect:from
  latest_version_segment: latest

output:
  dir: ./public

runtime:
  cache_dir: ./.cache/antora
  fetch: true
  log:
    level: debug

content:
  sources:
    - url: "."
      branches: HEAD
      start_path: test/fixtures/docs-site/example

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./test/fixtures/docs-site/supplemental-ui


antora:
  extensions:
    - require: "antora-highlightjs-extension"
      # error_on_unknown_language: true
      style: "dracula"
      # style: "darcula"
      # alias:
      #   plaintext: ['txt', 'text']
      #   shell: ['bash', 'sh', 'console']
      #   javascript: ['js']
      # treeview:
      #   enabled: false
      #   theme: "default"
